authors = ["Michael Krabbe Borregaard <mkborregaard@snm.ku.dk>"]
name = "MakieThemes"
uuid = "4307a514-e789-11e8-2e8d-7135958f4cf8"
version = "0.1.0"

[deps]

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
